package com.o2r.model;
// Generated Oct 23, 2016 4:48:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShippingAddress generated by hbm2java
 */
@Entity
@Table(name="shipping_address"
    ,catalog="o2rschema"
)
public class ShippingAddress  implements java.io.Serializable {


     private int shippingaddressId;
     private String name;
     private String addressline1;
     private String addressline2;
     private String addressline3;
     private String city;
     private String county;
     private String district;
     private String stateorregion;
     private String postalcode;
     private String countrycode;
     private String phone;
     private Integer shippingAddId;

    public ShippingAddress() {
    }

	
    public ShippingAddress(int shippingaddressId) {
        this.shippingaddressId = shippingaddressId;
    }
    public ShippingAddress(int shippingaddressId, String name, String addressline1, String addressline2, String addressline3, String city, String county, String district, String stateorregion, String postalcode, String countrycode, String phone, Integer shippingAddId) {
       this.shippingaddressId = shippingaddressId;
       this.name = name;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.addressline3 = addressline3;
       this.city = city;
       this.county = county;
       this.district = district;
       this.stateorregion = stateorregion;
       this.postalcode = postalcode;
       this.countrycode = countrycode;
       this.phone = phone;
       this.shippingAddId = shippingAddId;
    }
   
     @Id 

    
    @Column(name="SHIPPINGADDRESS_ID", unique=true, nullable=false)
    public int getShippingaddressId() {
        return this.shippingaddressId;
    }
    
    public void setShippingaddressId(int shippingaddressId) {
        this.shippingaddressId = shippingaddressId;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ADDRESSLINE1")
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    
    @Column(name="ADDRESSLINE2")
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    
    @Column(name="ADDRESSLINE3")
    public String getAddressline3() {
        return this.addressline3;
    }
    
    public void setAddressline3(String addressline3) {
        this.addressline3 = addressline3;
    }

    
    @Column(name="CITY")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="COUNTY")
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }

    
    @Column(name="DISTRICT")
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="STATEORREGION")
    public String getStateorregion() {
        return this.stateorregion;
    }
    
    public void setStateorregion(String stateorregion) {
        this.stateorregion = stateorregion;
    }

    
    @Column(name="POSTALCODE")
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    
    @Column(name="COUNTRYCODE")
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    
    @Column(name="PHONE")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="SHIPPING_ADD_ID")
    public Integer getShippingAddId() {
        return this.shippingAddId;
    }
    
    public void setShippingAddId(Integer shippingAddId) {
        this.shippingAddId = shippingAddId;
    }




}


